//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMotel.Data
{
    using System;
    
    public partial class GetDMOContracts
    {
        public int Contract_ID { get; set; }
        public string CICOID { get; set; }
        public string Fiscal_Year { get; set; }
        public string ATCode { get; set; }
        public string Project_Type { get; set; }
        public string Entity { get; set; }
    }
}
