//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMotel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMT_PCIS_Docs
    {
        public int PCIS_DocId { get; set; }
        public string CICOID { get; set; }
        public string FiscalYear { get; set; }
        public string ATCode { get; set; }
        public string PCIS_DocName { get; set; }
        public string PCIS_DocUrl { get; set; }
        public System.DateTime PCIS_DocDt { get; set; }
    
        public virtual HMT_Certifications HMT_Certifications { get; set; }
    }
}
