//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMotel.Data
{
    using System;
    
    public partial class pr_GetOrdinance_Result2
    {
        public string Paragraph { get; set; }
        public bool PCISRequired { get; set; }
        public Nullable<decimal> Tax_Rate { get; set; }
        public string AtCode { get; set; }
        public Nullable<System.DateTime> Ordinance_Date { get; set; }
        public bool P1_Complete { get; set; }
        public Nullable<bool> OrdinanceCorrect { get; set; }
        public Nullable<bool> CertTableMatchesOrdTable { get; set; }
        public Nullable<bool> CertRecordExists { get; set; }
    }
}
